stages:
  prepare:
    cmd: python src/data/prepare.py
    deps:
      - src/data/prepare.py
      - data/raw
    outs:
      - data/processed
    
  featurize:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data/processed
    outs:
      - data/features
    
  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/features
    outs:
      - models/model.pkl
    metrics:
      - models/metrics.json:
          cache: false
    
  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - models/model.pkl
      - data/features
    metrics:
      - models/evaluation.json:
          cache: false
