services:
  # Backend API service
  - type: web
    name: cdss-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn src.api.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true
    disk:
      name: models
      mountPath: /app/models
      sizeGB: 1

  # Frontend web service
  - type: web
    name: cdss-web
    env: docker
    dockerfilePath: ./Dockerfile.web.render
    dockerContext: .
    plan: starter
    healthCheckPath: /
    envVars:
      - key: API_URL
        fromService:
          name: cdss-api
          type: web
          property: url
    autoDeploy: true
